name = "CategoricalMonteCarlo"
uuid = "c43cd20a-c1d7-421d-b487-d45f18ab5186"
authors = ["Andrew J. Radcliffe <andrewjradcliffe@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
